### ISSUE TITLE
Question on the number of iteration

### ISSUE THREAD

**Issue by WonwoongCho** [betterze/StyleAlign#11]
Hello,

I am Wonwoong Cho, a phd student at Purdue University.
I have a question on the number of iteration for training a child model.
It may depend on a given dataset, but could you roughly let me know how many iterations did the child models in your paper go through? 

Thank you for reading my question!

I apologize for it if the information is already provided somewhere :(

**Comment by betterze** [comment]
We usually trained the child model until its FID or KID (number of images < 5K) converges.
