### ISSUE TITLE
How to search the direction using InterfaceGAN?

### ISSUE THREAD

**Issue by azaleasangel** [betterze/StyleAlign#9]
Hi, thanks for the great work!
I'm trying to reproduce the result of changing the pose on Human face and the Church (Figure 14).
As far as I understood, you use the InterFaceGAN to find the direction.
However, I looked into InterFaceGAN and found out they were built on StyleGAN instead of StyleGAN2.
Do you somehow adapt the weight to make the bonudary work with styleGAN2?
Or do you finetune the styleGAN in this case instead of StyleGAN2?

Thank you so much!

**Comment by betterze** [comment]
The [InterFaceGAN](https://github.com/genforce/interfacegan#prepare-data) method supports both StyleGAN1 and StyleGAN2. InterfaceGAN contains 3 steps:

1. Prepare data: Please use StyleGAN2 to generate a set of images. You could use the code from [StyleSpace](https://github.com/betterze/StyleSpace#localized-channels), and run 

'''
dataset_name='ffhq'
python GetCode.py --dataset_name $dataset_name --code_type 'w'
python GetCode.py --dataset_name $dataset_name --code_type 's'
python GetCode.py --dataset_name $dataset_name --code_type 'images_100K'
'''
2. Predict Attribute Score: I use this  [pose regressior](https://github.com/Ascend-Research/HeadPoseEstimation-WHENet).
3. Search Semantic Boundary: Same codes from InterfaceGAN

We aslo provide the pretrained models and pose direction in [here](https://drive.google.com/drive/u/1/folders/1MqCHQ6Yx-eon-3fu1g_AGjpyAUmzH6Jy). 

The 'ffhq' model is parent model, 'ffhq_pose' is the pose direction in w space, and 'ffhq_church' is the child model. We alse provide the grandchild model 'ffhq_church_ffhq256' grandchild model for reproducing [fig 34](https://openreview.net/pdf?id=Qg2vi4ZbHM9).

The 'ffhq512' is the parent model, 'ffhq512_pose' is the corresponding pose direction in w space, 'ffhq512_dog_bed' is the grandchild model for [fig 14](https://openreview.net/pdf?id=Qg2vi4ZbHM9).

**Comment by azaleasangel** [comment]
Hi @betterze,
Thank you so much for the quick response and detailed explanation!
I have one more question:
do you rewrite the stylegan_generator.py and stylegan_generator_model.py in InterFaceGAN for loading models of StyleGAN2?
Because this is the point I got stuck.
Do you modify those two files to get it work with edit.py?

Thank you so much!

**Comment by betterze** [comment]
InterfaceGan needs stylegan_generator.py and stylegan_generator_model.py for generating a set of w vectors and corresponding images. If we have other ways to a set of w vectors and corresponding images, then we dont need stylegan_generator.py and stylegan_generator_model.py any more.

To achieve this goal, just use the code from [StyleSpace](https://github.com/betterze/StyleSpace#localized-channels), and run:

'''
dataset_name='ffhq'
python GetCode.py --dataset_name $dataset_name --code_type 'w'
python GetCode.py --dataset_name $dataset_name --code_type 's'
python GetCode.py --dataset_name $dataset_name --code_type 'images_100K'
'''

You will get the w codes and images in ./npy/ffhq/ .

**Comment by azaleasangel** [comment]
Hi @betterze ,
Thank you so much, 
I think I now understand how to get it work.
I will play around a bit and see if I can recreate the results and then close this issue later.
Thanks again!

**Comment by azaleasangel** [comment]
Hi @betterze,
I can reproduce the results now, it's pretty cool!
Thanks a lot for your help!

btw, in Readme, there is one section called "sauge". Is it for "usage"?

**Comment by betterze** [comment]
sorry, I just change it. Thx
